// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isnqmzzelxecgstbtdgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzbnFtenplbHhlY2dzdGJ0ZGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODM1OTYsImV4cCI6MjA1ODc1OTU5Nn0.rKhLLAAtvJwj7CEC9YzP0m0weV9YkWrIx8zWGYQ2f0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);